### ISSUE TITLE
Instalação da tradução

### ISSUE THREAD

**Issue by augustoshoiti** [GMalvestiti/dawncraft_lang_pt_br#214]
Gostaria de saber como instalar a tradução, caso ela realmente esteja pronta. Não estou acostumado a jogar com mods, por isso sei muito pouco de como funciona.

**Comment by GMalvestiti** [comment]
A tradução ainda não está 100% pronta, porém já é possível usar.

Antes de tudo, feche o minecraft

Para instalar, faça o download da tradução nesse link: [https://github.com/GMalvestiti/dawncraft_lang_pt_br/archive/refs/heads/main.zip](url)

Depois, extraia o arquivo e, dentro da pasta extraída, copie as pastas: "config" e "global_packs"

Agora com as pastas copiadas, vá para o diretório onde o dawncraft está instalado e cole as pastas dentro desse diretório.

Depois, verifique se o idioma do jogo está para Português Brasileiro e também se em Pacotes de Recursos tem selecionado pacote com a bandeira do Brasil.

Um vídeo mostrando: [https://www.youtube.com/watch?v=bHq4xB3P-sg&pp=ygUUdHJhZHXDp8OjbyBkYXduY3JhZnQ%3D](url)
